apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ducptranpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ducptranpipelinesjavascriptdocker 
    spec:
      containers:
        - name: ducptranpipelinesjavascriptdocker 
          image: spacontainerregistry.azurecr.io/ducptranpipelinesjavascriptdocker
          ports:
          - containerPort: 8080